#!/bin/bash -e

URL="jp.archive.ubuntu.com"
REPOS="main universe multiverse restricted"

disable_repo() {
    lists=$(ls -d /etc/apt/sources.list.d/*.list 2>/dev/null | \
            fgrep -v cnc_updates | xargs)
    for list in ${lists}; do
        sed -i "s/^ *deb/#REPO# deb/g" ${list}
    done
    if [[ -e /etc/apt/sources.list ]]; then
        sed -i "s/^ *deb/#REPO# deb/g" /etc/apt/sources.list
    fi
}

cd $(dirname $0)

if [[ $(whoami) != "root" ]]; then
    echo "[ERR] script must be run as the root user, exit."
    exit 1
fi

disable_repo
tee /etc/apt/sources.list.d/REPO.list <<EOF >/dev/null
deb copy:$(pwd)/mirror/${URL}/ubuntu $(lsb_release -sc) ${REPOS}
deb copy:$(pwd)/mirror/${URL}/ubuntu $(lsb_release -sc)-updates ${REPOS}
deb copy:$(pwd)/mirror/${URL}/ubuntu $(lsb_release -sc)-backports ${REPOS}
deb copy:$(pwd)/mirror/${URL}/ubuntu $(lsb_release -sc)-security ${REPOS}
EOF
