#!/bin/bash -e

cd $(dirname $0)

if [[ $(whoami) == "root" ]]; then
    echo "[ERR] script must be run as NON-root user, exit."
    exit 1
fi

args=$(getopt -o "a" -l "all" -- $*)
set -- ${args}
while [[ $# -gt 0 ]]; do
    case "$1" in
    --all|-a)
        all="true";;
    --)
        shift; break;;
    esac
    shift
done

if [[ -n ${all} ]]; then
    rm -rf mirror/*
fi

rm -rf .var/*
